### ISSUE TITLE
Mapping Services to AWS Api Gateway

### ISSUE THREAD

**Issue by c0j0s** [CS3219-AY2324S1/ay2324s1-course-assessment-g05#111]
### Summary
Each service will need to prepend staging and domain to its endpoint paths.
Example: `/api/questions` -> `/question/api/questions`

### Background
Currently, AWS API gateway's endpoints comprise 3 components: `public-addr`, ~~`staging`~~ and `routes`. 
- public-addr is the publicly accessible URL for our frontends to consume
- ~~staging is used to identify the deployment environment for our APIs, we have `development` and `production` currently.~~
- routes basically define the resource paths of our micro-services. Ideally, we shouldn't need to change our services and hopes API gateway would help us map the public path to private paths which our services then could understand. **that's however not the case.....**

### ~~Problem 1~~ (Switching to multi-stack approach (2 different api gateway url for dev and prod respectively), dropping $stage in endpoints)
~~Instead of doing some conversion, the API gateway simply uses the routes defined as an access control list and simply throws the entire path to our containers directly.~~
Example:
1. ~~public request `id.public-addr.com/development/questions`,~~
2. ~~gateway checks for `/questions/` defined in routes for permission,~~
3. ~~gateway then throws `/development/questions` to question-service directly...~~
4. ~~question-service 404 lor, since it does not understand  `/development/questions`.~~

### Problem 2
Since we might have top-level resources like 'health' in our containers, mapping `/health` directly behind `/stage/health` would cause conflicts in gateway routes.

### Resolution
1. ~~So now the services need to handle staging values in the request path. we can simply replace the `/api` path with our staging value like this:~~

2. To resolve conflicts for our top-level paths, we'll need to introduce a `domain` value in our paths.
```ts
app.use(`/<DOMAIN>/api`, authMiddleware, router);
```

The routes in API gateway will be like this:
![image](https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g05/assets/7760148/d30ece1a-c2f0-4860-ad50-b1aba8bfdc89)

@tryyang2001  @weidak  @tlyi  @xingjie99 Take note of the changes 🫠

### Tracker
Backend:
- [x] question-service
- [x] matching-service
- [x] user-service
- [x] collaboration-service
- [x] auth-service
- [ ] history-service

Frontend:
- [x] endpoint.ts
- [x] question_api_warpper
- [x] matching_api_warpper
- [x] auth_api_warpper
- [x] collaboration_api_warpper
- [ ] history_api_warpper
- [x] user_api_warpper

**Comment by tryyang2001** [comment]
Understood, will change for user, question, and history!

**Comment by c0j0s** [comment]
> Understood, will change for user, question, and history!

I already made the changes to question-service.

**Comment by tryyang2001** [comment]
For the node env, is it fine if we used short form like:
- dev
- stg
- prd

Or we must use the whole word like:
- development
- staging/stage
- production

**Comment by c0j0s** [comment]
hmm... we can shorten it but we use the full term almost everywhere in `github-action` and `.env` already, a bit troublesome to change....

**Comment by tryyang2001** [comment]
OK sure, so let's use the full name. Shall we go with staging or stage?

**Comment by c0j0s** [comment]
oh staging is the term AWS use for this route pattern, so far I only configured `development` and `production`.

**Comment by tryyang2001** [comment]
Just fyi, `staging` is the environment that has thet same configuration as `production` but it is not the actual `production` environment. The reason why people use `staging` is to make sure all the code behaviour are expected.

I see, so we only need `development` and `production` right? I will configure the service with these 2. For small project like this, I don't think we need to set up staging env, unless it is very easy to have it haha.

**Comment by c0j0s** [comment]
Update:
1. HTTP path should follow this pattern `/${NODE_ENV}/${DOMAIN}/api/${PATHS}` moving forward.
2. Socket path should follow this pattern `/${NODE_ENV}/${DOMAIN}/socket/` instead to support proxy mapping.

**Comment by c0j0s** [comment]
Sorry guys, **another breaking change**. we will be switching to a duo stack deployment approach for aws, so the `stage`, aka `${NODE_ENV}` will be dropped. 

The previous idea is to use single stack deployment with a single API gateway URL that connects to a devCluster and prodCluster using `stage` separation. however, API gateway doesn't seem to support integration switching based on the deployment `stage`. 

So now we will be using two stacks instead, essentially having a separate API gateway and resources for `dev` and `prod` respectively.

![image](https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g05/assets/7760148/858e49aa-9a4b-4470-b556-5c8f631830ed)


Summary:
1. HTTP path should follow this pattern `/${DOMAIN}/api/${PATHS}` moving forward.
2. Socket path should follow this pattern `/${DOMAIN}/socket/` instead to support proxy mapping.

I already updated the files in the tracker list to the latest pattern in #106.

**Comment by weidak** [comment]
Ok! Thanks for all these... will migrate this asap

**Comment by tlyi** [comment]
Thanks a lot @c0j0s !! 👍 🤩
