### ISSUE TITLE
Sadly, AWS Api Gateway does not support Socket.io

### ISSUE THREAD

**Issue by c0j0s** [CS3219-AY2324S1/ay2324s1-course-assessment-g05#114]
See [this](https://stackoverflow.com/questions/70649284/aws-api-gateway-restful-api-socket-io-complains-about-error-route-socket-i)

We might need to migrate to the [WebSocket ](https://medium.com/hackernoon/websockets-api-gateway-9d4aca493d39)protocol instead. 
or we could expose matching-service ecs to public access, but this is cumbersome as we will be dealing with dynamic IP addresses for connection.

I'll migrate matching-service first to evaluate the effort needed before we make any final decision.

**Comment by weidak** [comment]
Have you seen http-proxy? Not sure if this will work: 

https://socket.io/docs/v3/reverse-proxy/

There are multiple posts stating it is possible to expose the server through API gateway, just that i cant find a solution... (like this in point 2. https://github.com/socketio/socket.io-client/issues/1370#issuecomment-864520133)

Configuring HTTP proxy:
https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-http.html

**Comment by c0j0s** [comment]
Sure, I'll try http-proxy out first

**Comment by c0j0s** [comment]
Seems like aws proxy path works with socket.io in transport mode, so no major change is required. 🙂
