### ISSUE TITLE
Internet is expensive!

### ISSUE THREAD

**Issue by c0j0s** [CS3219-AY2324S1/ay2324s1-course-assessment-g05#119]
### FYI

- Internet Gateway (IGW) allows instances with public IPs to access the internet.
- NAT Gateway (NGW) allows instances with no public IPs to access the internet.

### Issue
All ECS instances do not have public IPs as they are in `awsvpc` mode to support service integration with API Gateway.
So we need NAT Gateway (private subnet) with Internet Gateway (public subnet) to connect to external databases.
<img width="794" alt="image" src="https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g05/assets/7760148/e44fd63a-6440-4e4d-bfa0-98f4ef3f4824">

but
<img width="672" alt="image" src="https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g05/assets/7760148/bf7be075-84e9-4181-bc5c-ae3038cfb413">

Should we consider using AWS database solution or a container database instead?

Let's monitor the usage for a couple of days before we make any final decision.

**Comment by weidak** [comment]
50cents per api call HAHAHAHA I think hosting an AWS database will not be cheap either.. Maybe I should have let leyi set up the free tier 😢 Anyways since the services are going to be in ECS, i'm ok with a container database, just a bit more hassle to populate and maintain 2 different environments

**Comment by tryyang2001** [comment]
I see... Unfortunately, but we need to switch databases. As AWS ElasticCache is likely to be even more expensive, I think the alternative for Redis server will be a container database? Did I understand correctly? I don't mind maintaining 2 database in different environments, as we don't have the choice haha.

**Comment by weidak** [comment]
Yes, lets do that for redis..

**Comment by c0j0s** [comment]
Found the culprit (ECR) and managed to resolve it with `VPC Endpoint`. Normal traffic to our database shouldn't cost much and fargate tasks now cost more instead, so migrating to a container DB isn't necessary anymore I guess.

<img width="320" alt="image" src="https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g05/assets/7760148/941eee78-1982-46f9-8be3-4fe06862ebe8">


Case closed.
