### ISSUE TITLE
Finalise Auth for Assignment 3

### ISSUE THREAD

**Issue by tlyi** [CS3219-AY2324S1/ay2324s1-course-assessment-g05#124]
Tasks:
- [x] Write README for Auth
- [x] Video recording 
- [x] Fix strange behaviour on Login/Signup where the password field is cleared after pressing "Tab" and pressing "Enter" 
- [x] Implement error handling for Auth service
- [x] Write tests for Auth Service (at least for unit testing) 

If anyone has encountered any hiccups with Auth, please report :D

**Comment by tryyang2001** [comment]
Ops, I think I have committed the password-clearable thing in my [PR](https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g05/pull/127)... Sry!

**Comment by tlyi** [comment]
> Ops, I think I have committed the password-clearable thing in my [PR](https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g05/pull/127)... Sry!

Ahh!! Thank you :D
