### ISSUE TITLE
Bugs found on aws deployment

### ISSUE THREAD

**Issue by weidak** [CS3219-AY2324S1/ay2324s1-course-assessment-g05#137]
- [ ] Frequent disconnections from socket in collaboration service
  - Need to further investigate, maybe just sch wifi cmi
  - When 2 users are collaborating at the same time, it seems to be working fine sometimes, just a bit inconsistent.

Update:

The issue may be caused by proxying + pooling in API gateway, where API gateway will terminate the connections after a certain time. Load balancing also may be redirecting requests and not maintaining HTTP long polling connection. There are two solutions to this:

1. Changing from SocketIO to WebSocket for node:
- API Gateway supports WebSocket API where we can just use $connect, $disconnect etc.
- May be a huge overhaul of implementation and cause more issues, and may not guarantee it

2. Upgrading from using a central server to P2P connections:
- Use central server as a caching mechanism and retrieve session details
- Events are directly emitted to client: 

Previously:
**Client1** -(Events)-> **Server** -(Events)-> **Client2**

New way under (2)
**Server** <-(Cache)- **Client1** <- (Events) -> **Client2** -(Cache)-> **Server**

- [x] Profile dp file size exceed limits only works once, subsequent times toast does not show
  - For the first upload, the toast appears stating that the file size exceeds the 3MB. But subsequent images that exceed 3MB does not show
  
- [x] Make edit profile dp more obvious, and more intuitive (like adding an edit button to the dp and have a spinner while the new img uploads)

- [x] Signup still does not work on cloud deployment
  - it still passes http://localhost for the clicking of email verification link @tlyi @xingjie99 will this be a quick fix?

**Comment by tlyi** [comment]
Ooh good catch, sorry will update the verification link!
