### ISSUE TITLE
Strange bug, issue with rendering dashboard after navigating to past attemps page and return to dashboard by pressing backward button.

### ISSUE THREAD

**Issue by c0j0s** [CS3219-AY2324S1/ay2324s1-course-assessment-g05#142]
Happens only in amplify.

Enter through here:
<img width="553" alt="image" src="https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g05/assets/7760148/dcfc1f5e-442d-4036-861f-fb1dc9208f7d">

then press backward in the browser:
<img width="809" alt="image" src="https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g05/assets/7760148/ac69b3d1-682e-4137-9f02-f28ce24dfef0">

Navigating and returning from other pages seems fine.

**Comment by weidak** [comment]
Wtf.... ok i will remove/redo the button

**Comment by weidak** [comment]
Same for this: (Click into any past attempt)

![image](https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g05/assets/70256674/4c74bd20-a49e-4ff5-a20d-329f81e6f2da)

Press back:
![image](https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g05/assets/70256674/8bb3817a-e9da-4269-93b7-0cf3377daa7d)

**Comment by weidak** [comment]
Bug no longer exists with latest builds, can try [here](https://master.d2wfcislijzove.amplifyapp.com/)
