### ISSUE TITLE
Create a script to convert question details from the .pdf/.txt file to json

### ISSUE THREAD

**Issue by tryyang2001** [CS3219-AY2324S1/ay2324s1-course-assessment-g05#23]
## Why is this needed?
- we need a way to convert the question details we have in `CS3219Assignments.pdf` into json format with fields like `questionId`, `title`, `description`, `topics`, `complexity`, `url`, `examples`, and `constraints`.

## How can this be done?
- my current idea is to first convert the pdf into a txt file, and then write a python script to process the string. Any better idea will be welcomed!

**Comment by c0j0s** [comment]
hmm....... there isn't any requirement for us to input every question from the pdf, so I guess we can do manual for few questions first? not worth the effort to automate it.

**Comment by tryyang2001** [comment]
Agree... I actually spend my morning trying to create such script. However, the script does not run very successful due to the data in the pdf is quite messy, like some of the data span across two rows, and then the format is not always the same. And the conversion from pdf to txt file also cause some inconsistency between the layout, and some characters are missing :(
So eventually I just manually typed all 20 questions into a json format. 

> there isn't any requirement for us to input every question from the pdf

Ah my bad, I thought we must insert all 20 questions into the database... 

And the good news is, this is not an issue anymore, I will close this.
