### ISSUE TITLE
Inconsistency between the `Topic` in `Leetcode` and the `Pdf`

### ISSUE THREAD

**Issue by tryyang2001** [CS3219-AY2324S1/ay2324s1-course-assessment-g05#24]
## What is the problem?

As mentioned [here](https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g05/pull/22#discussion_r1324669988), we plan to use the `Topic` enum declared by @c0j0s when he was working on his question-related frontend. However, after going through the topics in `Leetcode` and the given pdf data, I noticed that the topics are not similar. 

### Screenshot for Leetcode topics
![image](https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g05/assets/69421979/f955a30d-e266-4cae-a1c4-c2f7ed6b1c1d)

### Some examples of the different topics in the pdf
![image](https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g05/assets/69421979/2a8099de-2f55-4c9b-be54-13093c5a57c0)
We don't have a specific topic for "data structure", "databases", "algorithms", etc. 

## Question to discuss
The question is, which format shall we follow? I will suggest that we follow Leetcode one. If you all agree, I will update the enum. Any idea?

**Comment by c0j0s** [comment]
I guess following the leetcode ones would be better since we will be scrapping questions from there lateron anyway for assignment 6.
