### ISSUE TITLE
Create ui components for Matching Service

### ISSUE THREAD

**Issue by c0j0s** [CS3219-AY2324S1/ay2324s1-course-assessment-g05#26]
Based on the software requirements defined:

![image](https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g05/assets/7760148/ea0b7b2f-eecc-45a7-803c-3ee43a349996)![image](https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g05/assets/7760148/a33cd733-504c-439c-ae38-14e23e28e714)

and a rough feature flow for the matching service:
![image](https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g05/assets/7760148/8c5a5325-7fec-4d08-b2cb-994f9183d7c3)

These will be the UI components needed:
- [x] Quick Match Button
- [x] Matching Card
![image](https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g05/assets/7760148/1e736055-5e49-4d18-b40e-507fe034969b)
- [ ] Wating lobby modal + retry prompt

**Comment by tlyi** [comment]
Oh!! For the first 2 components  "Quick Match Button" and "Matching Card", I have already included them in my PR #27.
