### ISSUE TITLE
Discussion for the `api()` method in `endpoint.ts`

### ISSUE THREAD

**Issue by tryyang2001** [CS3219-AY2324S1/ay2324s1-course-assessment-g05#41]
## Problem Description
Hi @c0j0s, I went through the code for `api()` method in `endpoint.ts` and have a few questions that need some clarifications:

### 1. Service URL and port number are dynamically assigned every time we call this method
I noticed in the `api` method, that the domain URL and the port numbers need to be dynamically assigned every time we call this method. However, consider our use case, where for each service, we know the port number and it will not be changed. Do you want to change your code such that we define the service URL and port number in each `api_wrapper` file instead of assigning them in the API call? See the screenshot below:
![image](https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g05/assets/69421979/4ac5ef78-850c-429e-8ef0-3497c4df744f)

### 2. No way to change the request header in each service
Correct me if my understanding is wrong. According to the current implementation, there is no flexibility in changing the request headers. Allow the caller to change the request header will be helpful especially when writing the integration test. And there is no guarantee that the headers needed in each service will be the same in the future. Hence, I will suggest we let the caller to provide additional headers. What do you think?
![image](https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g05/assets/69421979/5e0e6030-8795-4a9d-84f2-0cd23fe00869)

**Comment by c0j0s** [comment]
1. the idea here is for the endpoint layer to access environment-related information only, we certainly do not want config-related values in our code so these values should be in an environment file (useful for dockerisation as well). another way is to retrieve env values in the wrapper layer and pass it down the endpoint layer, but this approach exposes the wrapper layer to unnecessary system or environment setup details. so to separate and simplify their roles, the endpoint layer deals with all those setup details while the wrapper layer only needs to know what service to consume.
2. sure no problem.

**Comment by tryyang2001** [comment]
Ok got it. So the idea is to separate all the API wrappers with the environmental information. The tradeoff is that the endpoint call might be a little bit slower, but I think this extra latency is still acceptable. So I agree to continue using this approach! Thanks for the detailed explanation.
