### ISSUE TITLE
Relax word limit for question description.

### ISSUE THREAD

**Issue by c0j0s** [CS3219-AY2324S1/ay2324s1-course-assessment-g05#43]
See #32 issue 2

**Comment by tryyang2001** [comment]
I see, I overlook that the description can contain URL... 
Working on the changes now!

**Comment by tryyang2001** [comment]
I have created a [PR](https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g05/pull/44) for the fix, can you help review and approve? Thanks!
