### ISSUE TITLE
Discussion for ways of handling erroneous response status code

### ISSUE THREAD

**Issue by tryyang2001** [CS3219-AY2324S1/ay2324s1-course-assessment-g05#47]
## About the issue
When we sent a request to backend server API, there is a chance that the response status code is 4xx or 5xx. I would like to standardize how we are going to handle the situation when we get such status code.

## Aproach 1: Create custom typed object and let the api_wrapper returns it on error
This is the current implementation in our master. The logic in each `api_wrapper` method is that if the response status code is not the one we are expecting, we return the error type object with `ok` set to `false` and `message` set to the error message (eg: question with this id not found, duplicated question, etc.).

**Pros**: On the frontend page component side and the `api_wrapper` side, error handling is short and simple. (feel free to add more)

**Cons**: Hard to distinguish different status codes, the only way we can distinguish is by looking at the `response.message`. Or we need to check something that should exist does not exist, which is not very straightforward.
![image](https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g05/assets/69421979/41bd7818-7df2-4010-b979-cef7f608ffba)

## Aproach 2: Create custom error for different status code and throw the error
For this implementation, you may refer to this side branch [user_api_wrapper.tsx ](https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g05/blob/45-integrate-user-service-with-frontend-dashboard/frontend/src/helpers/user/user_api_wrappers.tsx) implementation. The idea is that when we receive different status code, we throw a specific error accordingly.

**Pros**: Now the error handling will be quite straightforward. Let's say we are calling `getQuestionById` and we receive 404, we throw the `NotFoundError` and then on the frontend page component side, we can catch this error and display a meaningful error message to our user (either through a toaster or any other format). (feel free to add more)

**Cons**: Long code, leaving try-catch to frontend component side. Also, 4xx is actually not supposed to be a system error to be thrown, it is most likely a user error.
![image](https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g05/assets/69421979/4a9e524e-4f16-48d2-a372-5e6966164448)

**Comment by c0j0s** [comment]
The second approach seems to be a better approach. the current approach only tells the view if the call is a success or not, might not be good if we want to prompt different error feedbacks for different response statuses.

As for the second approach, I'll probably do this to simplify the code:
<img width="348" alt="image" src="https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g05/assets/7760148/7b6f74dc-7c7b-495b-aa1b-209c77112e72">

**Comment by tryyang2001** [comment]
Oh thanks for your suggestion, by following your way (shown in the screenshot above), the code is easier to read! I will follow your way too in user_api_wrapper.

**Comment by c0j0s** [comment]
Just to follow up, seems like this pattern is not supported for server actions. the client component is unable to catch custom error types. Server actions are more akin to backend handlers than local functions, so status updates should be either reflected as a response status code or payload to the client component I guess.

That's why in the problem wrapper I simply return the `ApiRespones` from the endpoint. 🙄

**Comment by tryyang2001** [comment]
I see. I tested this on my side and I encountered the same issue that you mentioned. I am fine with returning an empty ApiResponse for question_api_wrappers then. Thank you for bringing this out!

**Comment by tryyang2001** [comment]
Closes this as we have agreed with a solution:
- except question service, all other frontend API wrappers will throw custom error
- question service will return ApiResponse on error
