### ISSUE TITLE
Define entities for assignment 1/2

### ISSUE THREAD

**Issue by c0j0s** [CS3219-AY2324S1/ay2324s1-course-assessment-g05#5]
Hi guys, lets start by defining our preliminary entities for assignment 1/2.

### Question
```
{
    id: str
    title: str
    description: str
    category: str
    complexity: str (easy/medium/hard)
    status: str (draft/publish/deleted)
    createdOn: date
    updatedOn: date (optional)
    author: str (userid)
    url: str (leetcode-link)
}
```
### User
```
{
    id: str
    image: str
    name: str
    email: str
    password: str (hashed)
    role: str
    status: str (active/inactive)
    createdOn: date
}
```

Above are some attributes I could think of, what u guys think?

**Comment by weidak** [comment]
These attributes look good! Minor detail but should id for both user and question should be numeric based instead of string? Also, according to appendix 1, we also require `url: str` in the questions entity to link to the leetcode question.

**Comment by tryyang2001** [comment]
I'm not 100% sure, but my guess is that the id should be a `string`, and it should be a randomly generated alphanumeric ID, not just a pure integer value. I am suggesting this because by doing this way, we don't need to keep track of the ID count when we want to either create/delete an instance.

**Comment by tryyang2001** [comment]
@c0j0s Thanks for creating this issue. The structure looks good to me in general. But I do have questions and some suggestions:
1. Regarding the `Question` type, may I ask what is the purpose of the `content` attribute? It seems like the question description, constraints, and examples should be inside the `description` attribute already, did I miss anything?
2. I am still thinking what kind of user data we need to collect when we let the user sign up for a new account. But for OAuth login, let's say Google, we will be able to obtain information like the user email, name, image (profile photo), and etc. So I am suggesting to add more attributes like `name` and `image`.
3. If we have plan to allow user to login by using an (email, password) pair, we need to store the hashed password. So we should include another attribute `password` in `User`. Furthermore, as we implement the password feature, we will also need to implement the reset password feature. To do this, we need a `forgetPasswordToken` and `forgetPasswordTokenExpiry` in our `User` database. Need more discussion. 
4. Some of the attributes can be marked as optional, for example the `updatedAt` attribute in `Question`. The backend team need to discuss more about this before implementing :P.

**Comment by c0j0s** [comment]
> @c0j0s Thanks for creating this issue. The structure looks good to me in general. But I do have questions and some suggestions:
> 
> 1. Regarding the `Question` type, may I ask what is the purpose of the `content` attribute? It seems like the question description, constraints, and examples should be inside the `description` attribute already, did I miss anything?
> 2. I am still thinking what kind of user data we need to collect when we let the user sign up for a new account. But for OAuth login, let's say Google, we will be able to obtain information like the user email, name, image (profile photo), and etc. So I am suggesting to add more attributes like `name` and `image`.
> 3. If we have plan to allow user to login by using an (email, password) pair, we need to store the hashed password. So we should include another attribute `password` in `User`. Furthermore, as we implement the password feature, we will also need to implement the reset password feature. To do this, we need a `forgetPasswordToken` and `forgetPasswordTokenExpiry` in our `User` database. Need more discussion.
> 4. Some of the attributes can be marked as optional, for example the `updatedAt` attribute in `Question`. The backend team need to discuss more about this before implementing :P.

1.  oh my bad, I misread the description.  

2.3.4:
Sure, I guess we can assume an email/password setup first for as1/2? We can refine it once we are ready for as3.

**Comment by tlyi** [comment]
Looks good for a start! One minor suggestion is to change the type of variables with fixed values (such as complexity and status) to enums to ensure strict typing.

**Comment by tryyang2001** [comment]
> One minor suggestion is to change the type of variables with fixed values (such as complexity and status) to enums to ensure strict typing.

@tlyi Sure, thanks for the suggestion, we will declare `enums` for those specific attributes during the implementation!

**Comment by weidak** [comment]
Closing this discussion thread to start making tickets/issues
