### ISSUE TITLE
Resolve issues with Profile CRUD caused by AuthContext

### ISSUE THREAD

**Issue by tlyi** [CS3219-AY2324S1/ay2324s1-course-assessment-g05#61]
Sorry!! Forgot to check the impact on the login/signup functions before merging my PR yesterday :(

**Comment by tryyang2001** [comment]
Hi, yes so the issue is that the dashboard, profile pages are not rendering the correct user data. Thanks for fixing this!

**Comment by tlyi** [comment]
> Hi, yes so the issue is that the dashboard, profile pages are not rendering the correct user data. Thanks for fixing this!

Yes sorry 😢  I have made the relevant fixes, please check it out!
