### ISSUE TITLE
Implement tests and error handling for collaboration service (Caching)

### ISSUE THREAD

**Issue by weidak** [CS3219-AY2324S1/ay2324s1-course-assessment-g05#82]
- On exit/page refresh, restore code (Cache)
- On disconnect, attempt to reconnect
- Ensure backend has tests ready and integrate it into github actions

**Comment by tryyang2001** [comment]
Closed this issue as the related [PR ](https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g05/pull/103) has been merged to master.
