### ISSUE TITLE
Implement getQuestionByPreference and update question services

### ISSUE THREAD

**Issue by c0j0s** [CS3219-AY2324S1/ay2324s1-course-assessment-g05#91]
Main task:
- [x] Implement getQuestionByPreference in FE question wrapper layer.
- [x] Consume new API from question service.

Others:
- [x] Fix constraints input field issues.
- [x] Update wrapper layer implementation.
- [x] Add UI feedback for event status.

Hold:
- [ ] Protect question routes. (wait for session authentication)

**Comment by tryyang2001** [comment]
Why do you need to create the `getQuestionByPreference` endpoint? You can use the `getQuestions` endpoint and providing the query parameters, such as `topics` and `complexities`/`difficulties`, and I believe that's all right?

**Comment by tryyang2001** [comment]
The `getQuestions` endpoint support filters. However, it does not return the question detail in full. So it only returns the question id, title, topics, complexity. Considering the matching use case, we only need to return the question id, so I guess it will be sufficient right?

**Comment by c0j0s** [comment]
Yes questionId is sufficient.

**Comment by tryyang2001** [comment]
Got it, thanks for confirming! 😃

**Comment by c0j0s** [comment]
@tryyang2001 currently `getQuestion` supports array filters for the topics field, which is perfect for my `getQuestionByPreference`.

`?topics=ARRAY&complexity=EASY&complexity=MEDIUM`
however, it seems like zod is blocking the array filter for the complexity field, the matching might want to query questions from multiple complexity levels. 

is it possible to add support for complexity? else I'll just do multiple calls then.

**Comment by tryyang2001** [comment]
@c0j0s Oh my bad, it is possible to support complexity as an array! I will do the fix now!
