### ISSUE TITLE
[Question Service] UpdateQuestionValidator doesnt seem to enforce `.min(3)` rule 

### ISSUE THREAD

**Issue by c0j0s** [CS3219-AY2324S1/ay2324s1-course-assessment-g05#97]
Strange error, the `UpdateQuestionValidator` works for title but not description.
<img width="357" alt="image" src="https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g05/assets/7760148/8b21996b-9288-432d-be43-fe6fbaecf417">

<img width="266" alt="image" src="https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g05/assets/7760148/a785ac33-c138-438a-ae43-425ccefd5e8f">

@tryyang2001 can you take a look?

**Comment by tryyang2001** [comment]
I see, the reason is that since we are using react quill (is this the right name xD) in description, so it will convert the text to something like `<p>1</p>`, and when saved this as a string, it is more than 3 characters so the backend accepts it.

**Comment by c0j0s** [comment]
I see

**Comment by tryyang2001** [comment]
My plan for the fix is to check that the input description without the the HTML tags is more than a certain threshold, so I will update my validator haha.

**Comment by c0j0s** [comment]
wah then you will need a html parser in backend...
just leave it bah, since its an admin function anyway, the validation can be less strict 🤔
low-priority stuff also.

**Comment by tryyang2001** [comment]
Oh this can be done by using regular expression too since I am receiving the `description` as a string haha. I have it working already, just that I want to create some test cases to confirm the behaviour.
